
class dict:
  dictionary={

"__assert_fail":["void","(const char *, const char *, unsigned int, const char *)"],
"__assert_perror_fail":["void","(int, const char *, unsigned int, const char *)"],
"__assert":["void","(const char *, const char *, int)"],
"__ctype_b_loc":["const unsigned short **","()"],
"__ctype_tolower_loc":["const __int32_t **","()"],
"__ctype_toupper_loc":["const __int32_t **","()"],
"isalnum":["int","(int)"],
"isalpha":["int","(int)"],
"iscntrl":["int","(int)"],
"isdigit":["int","(int)"],
"islower":["int","(int)"],
"isgraph":["int","(int)"],
"isprint":["int","(int)"],
"ispunct":["int","(int)"],
"isspace":["int","(int)"],
"isupper":["int","(int)"],
"isxdigit":["int","(int)"],
"tolower":["int","(int)"],
"toupper":["int","(int)"],
"isblank":["int","(int)"],
"isascii":["int","(int)"],
"toascii":["int","(int)"],
"_toupper":["int","(int)"],
"_tolower":["int","(int)"],
"isalnum_l":["int","(int, locale_t)"],
"isalpha_l":["int","(int, locale_t)"],
"iscntrl_l":["int","(int, locale_t)"],
"isdigit_l":["int","(int, locale_t)"],
"islower_l":["int","(int, locale_t)"],
"isgraph_l":["int","(int, locale_t)"],
"isprint_l":["int","(int, locale_t)"],
"ispunct_l":["int","(int, locale_t)"],
"isspace_l":["int","(int, locale_t)"],
"isupper_l":["int","(int, locale_t)"],
"isxdigit_l":["int","(int, locale_t)"],
"isblank_l":["int","(int, locale_t)"],
"__tolower_l":["int","(int, locale_t)"],
"tolower_l":["int","(int, locale_t)"],
"__toupper_l":["int","(int, locale_t)"],
"toupper_l":["int","(int, locale_t)"],
"__errno_location":["int *","()"],
"setlocale":["char *","(int, const char *)"],
"localeconv":["struct lconv *","()"],
"newlocale":["locale_t","(int, const char *, locale_t)"],
"duplocale":["locale_t","(locale_t)"],
"freelocale":["void","(locale_t)"],
"uselocale":["locale_t","(locale_t)"],
"__fpclassify":["int","(double)"],
"__signbit":["int","(double)"],
"__isinf":["int","(double)"],
"__finite":["int","(double)"],
"__isnan":["int","(double)"],
"__iseqsig":["int","(double, double)"],
"__issignaling":["int","(double)"],
"acos":["double","(double)"],
"__acos":["double","(double)"],
"asin":["double","(double)"],
"__asin":["double","(double)"],
"atan":["double","(double)"],
"__atan":["double","(double)"],
"atan2":["double","(double, double)"],
"__atan2":["double","(double, double)"],
"cos":["double","(double)"],
"__cos":["double","(double)"],
"sin":["double","(double)"],
"__sin":["double","(double)"],
"tan":["double","(double)"],
"__tan":["double","(double)"],
"cosh":["double","(double)"],
"__cosh":["double","(double)"],
"sinh":["double","(double)"],
"__sinh":["double","(double)"],
"tanh":["double","(double)"],
"__tanh":["double","(double)"],
"acosh":["double","(double)"],
"__acosh":["double","(double)"],
"asinh":["double","(double)"],
"__asinh":["double","(double)"],
"atanh":["double","(double)"],
"__atanh":["double","(double)"],
"exp":["double","(double)"],
"__exp":["double","(double)"],
"frexp":["double","(double, int *)"],
"__frexp":["double","(double, int *)"],
"ldexp":["double","(double, int)"],
"__ldexp":["double","(double, int)"],
"log":["double","(double)"],
"__log":["double","(double)"],
"log10":["double","(double)"],
"__log10":["double","(double)"],
"modf":["double","(double, double *)"],
"__modf":["double","(double, double *)"],
"expm1":["double","(double)"],
"__expm1":["double","(double)"],
"log1p":["double","(double)"],
"__log1p":["double","(double)"],
"logb":["double","(double)"],
"__logb":["double","(double)"],
"exp2":["double","(double)"],
"__exp2":["double","(double)"],
"log2":["double","(double)"],
"__log2":["double","(double)"],
"pow":["double","(double, double)"],
"__pow":["double","(double, double)"],
"sqrt":["double","(double)"],
"__sqrt":["double","(double)"],
"hypot":["double","(double, double)"],
"__hypot":["double","(double, double)"],
"cbrt":["double","(double)"],
"__cbrt":["double","(double)"],
"ceil":["double","(double)"],
"__ceil":["double","(double)"],
"fabs":["double","(double)"],
"__fabs":["double","(double)"],
"floor":["double","(double)"],
"__floor":["double","(double)"],
"fmod":["double","(double, double)"],
"__fmod":["double","(double, double)"],
"isinf":["int","(double)"],
"finite":["int","(double)"],
"drem":["double","(double, double)"],
"__drem":["double","(double, double)"],
"significand":["double","(double)"],
"__significand":["double","(double)"],
"copysign":["double","(double, double)"],
"__copysign":["double","(double, double)"],
"nan":["double","(const char *)"],
"__nan":["double","(const char *)"],
"isnan":["int","(double)"],
"j0":["double","(double)"],
"__j0":["double","(double)"],
"j1":["double","(double)"],
"__j1":["double","(double)"],
"jn":["double","(int, double)"],
"__jn":["double","(int, double)"],
"y0":["double","(double)"],
"__y0":["double","(double)"],
"y1":["double","(double)"],
"__y1":["double","(double)"],
"yn":["double","(int, double)"],
"__yn":["double","(int, double)"],
"erf":["double","(double)"],
"__erf":["double","(double)"],
"erfc":["double","(double)"],
"__erfc":["double","(double)"],
"lgamma":["double","(double)"],
"__lgamma":["double","(double)"],
"tgamma":["double","(double)"],
"__tgamma":["double","(double)"],
"gamma":["double","(double)"],
"__gamma":["double","(double)"],
"lgamma_r":["double","(double, int *)"],
"__lgamma_r":["double","(double, int *)"],
"rint":["double","(double)"],
"__rint":["double","(double)"],
"nextafter":["double","(double, double)"],
"__nextafter":["double","(double, double)"],
"nexttoward":["double","(double, long double)"],
"__nexttoward":["double","(double, long double)"],
"remainder":["double","(double, double)"],
"__remainder":["double","(double, double)"],
"scalbn":["double","(double, int)"],
"__scalbn":["double","(double, int)"],
"ilogb":["int","(double)"],
"__ilogb":["int","(double)"],
"scalbln":["double","(double, long)"],
"__scalbln":["double","(double, long)"],
"nearbyint":["double","(double)"],
"__nearbyint":["double","(double)"],
"round":["double","(double)"],
"__round":["double","(double)"],
"trunc":["double","(double)"],
"__trunc":["double","(double)"],
"remquo":["double","(double, double, int *)"],
"__remquo":["double","(double, double, int *)"],
"lrint":["long","(double)"],
"__lrint":["long","(double)"],
"llrint":["long long","(double)"],
"__llrint":["long long","(double)"],
"lround":["long","(double)"],
"__lround":["long","(double)"],
"llround":["long long","(double)"],
"__llround":["long long","(double)"],
"fdim":["double","(double, double)"],
"__fdim":["double","(double, double)"],
"fmax":["double","(double, double)"],
"__fmax":["double","(double, double)"],
"fmin":["double","(double, double)"],
"__fmin":["double","(double, double)"],
"fma":["double","(double, double, double)"],
"__fma":["double","(double, double, double)"],
"scalb":["double","(double, double)"],
"__scalb":["double","(double, double)"],
"__fpclassifyf":["int","(float)"],
"__signbitf":["int","(float)"],
"__isinff":["int","(float)"],
"__finitef":["int","(float)"],
"__isnanf":["int","(float)"],
"__iseqsigf":["int","(float, float)"],
"__issignalingf":["int","(float)"],
"acosf":["float","(float)"],
"__acosf":["float","(float)"],
"asinf":["float","(float)"],
"__asinf":["float","(float)"],
"atanf":["float","(float)"],
"__atanf":["float","(float)"],
"atan2f":["float","(float, float)"],
"__atan2f":["float","(float, float)"],
"cosf":["float","(float)"],
"__cosf":["float","(float)"],
"sinf":["float","(float)"],
"__sinf":["float","(float)"],
"tanf":["float","(float)"],
"__tanf":["float","(float)"],
"coshf":["float","(float)"],
"__coshf":["float","(float)"],
"sinhf":["float","(float)"],
"__sinhf":["float","(float)"],
"tanhf":["float","(float)"],
"__tanhf":["float","(float)"],
"acoshf":["float","(float)"],
"__acoshf":["float","(float)"],
"asinhf":["float","(float)"],
"__asinhf":["float","(float)"],
"atanhf":["float","(float)"],
"__atanhf":["float","(float)"],
"expf":["float","(float)"],
"__expf":["float","(float)"],
"frexpf":["float","(float, int *)"],
"__frexpf":["float","(float, int *)"],
"ldexpf":["float","(float, int)"],
"__ldexpf":["float","(float, int)"],
"logf":["float","(float)"],
"__logf":["float","(float)"],
"log10f":["float","(float)"],
"__log10f":["float","(float)"],
"modff":["float","(float, float *)"],
"__modff":["float","(float, float *)"],
"expm1f":["float","(float)"],
"__expm1f":["float","(float)"],
"log1pf":["float","(float)"],
"__log1pf":["float","(float)"],
"logbf":["float","(float)"],
"__logbf":["float","(float)"],
"exp2f":["float","(float)"],
"__exp2f":["float","(float)"],
"log2f":["float","(float)"],
"__log2f":["float","(float)"],
"powf":["float","(float, float)"],
"__powf":["float","(float, float)"],
"sqrtf":["float","(float)"],
"__sqrtf":["float","(float)"],
"hypotf":["float","(float, float)"],
"__hypotf":["float","(float, float)"],
"cbrtf":["float","(float)"],
"__cbrtf":["float","(float)"],
"ceilf":["float","(float)"],
"__ceilf":["float","(float)"],
"fabsf":["float","(float)"],
"__fabsf":["float","(float)"],
"floorf":["float","(float)"],
"__floorf":["float","(float)"],
"fmodf":["float","(float, float)"],
"__fmodf":["float","(float, float)"],
"isinff":["int","(float)"],
"finitef":["int","(float)"],
"dremf":["float","(float, float)"],
"__dremf":["float","(float, float)"],
"significandf":["float","(float)"],
"__significandf":["float","(float)"],
"copysignf":["float","(float, float)"],
"__copysignf":["float","(float, float)"],
"nanf":["float","(const char *)"],
"__nanf":["float","(const char *)"],
"isnanf":["int","(float)"],
"j0f":["float","(float)"],
"__j0f":["float","(float)"],
"j1f":["float","(float)"],
"__j1f":["float","(float)"],
"jnf":["float","(int, float)"],
"__jnf":["float","(int, float)"],
"y0f":["float","(float)"],
"__y0f":["float","(float)"],
"y1f":["float","(float)"],
"__y1f":["float","(float)"],
"ynf":["float","(int, float)"],
"__ynf":["float","(int, float)"],
"erff":["float","(float)"],
"__erff":["float","(float)"],
"erfcf":["float","(float)"],
"__erfcf":["float","(float)"],
"lgammaf":["float","(float)"],
"__lgammaf":["float","(float)"],
"tgammaf":["float","(float)"],
"__tgammaf":["float","(float)"],
"gammaf":["float","(float)"],
"__gammaf":["float","(float)"],
"lgammaf_r":["float","(float, int *)"],
"__lgammaf_r":["float","(float, int *)"],
"rintf":["float","(float)"],
"__rintf":["float","(float)"],
"nextafterf":["float","(float, float)"],
"__nextafterf":["float","(float, float)"],
"nexttowardf":["float","(float, long double)"],
"__nexttowardf":["float","(float, long double)"],
"remainderf":["float","(float, float)"],
"__remainderf":["float","(float, float)"],
"scalbnf":["float","(float, int)"],
"__scalbnf":["float","(float, int)"],
"ilogbf":["int","(float)"],
"__ilogbf":["int","(float)"],
"scalblnf":["float","(float, long)"],
"__scalblnf":["float","(float, long)"],
"nearbyintf":["float","(float)"],
"__nearbyintf":["float","(float)"],
"roundf":["float","(float)"],
"__roundf":["float","(float)"],
"truncf":["float","(float)"],
"__truncf":["float","(float)"],
"remquof":["float","(float, float, int *)"],
"__remquof":["float","(float, float, int *)"],
"lrintf":["long","(float)"],
"__lrintf":["long","(float)"],
"llrintf":["long long","(float)"],
"__llrintf":["long long","(float)"],
"lroundf":["long","(float)"],
"__lroundf":["long","(float)"],
"llroundf":["long long","(float)"],
"__llroundf":["long long","(float)"],
"fdimf":["float","(float, float)"],
"__fdimf":["float","(float, float)"],
"fmaxf":["float","(float, float)"],
"__fmaxf":["float","(float, float)"],
"fminf":["float","(float, float)"],
"__fminf":["float","(float, float)"],
"fmaf":["float","(float, float, float)"],
"__fmaf":["float","(float, float, float)"],
"scalbf":["float","(float, float)"],
"__scalbf":["float","(float, float)"],
"__fpclassifyl":["int","(long double)"],
"__signbitl":["int","(long double)"],
"__isinfl":["int","(long double)"],
"__finitel":["int","(long double)"],
"__isnanl":["int","(long double)"],
"__iseqsigl":["int","(long double, long double)"],
"__issignalingl":["int","(long double)"],
"acosl":["long double","(long double)"],
"__acosl":["long double","(long double)"],
"asinl":["long double","(long double)"],
"__asinl":["long double","(long double)"],
"atanl":["long double","(long double)"],
"__atanl":["long double","(long double)"],
"atan2l":["long double","(long double, long double)"],
"__atan2l":["long double","(long double, long double)"],
"cosl":["long double","(long double)"],
"__cosl":["long double","(long double)"],
"sinl":["long double","(long double)"],
"__sinl":["long double","(long double)"],
"tanl":["long double","(long double)"],
"__tanl":["long double","(long double)"],
"coshl":["long double","(long double)"],
"__coshl":["long double","(long double)"],
"sinhl":["long double","(long double)"],
"__sinhl":["long double","(long double)"],
"tanhl":["long double","(long double)"],
"__tanhl":["long double","(long double)"],
"acoshl":["long double","(long double)"],
"__acoshl":["long double","(long double)"],
"asinhl":["long double","(long double)"],
"__asinhl":["long double","(long double)"],
"atanhl":["long double","(long double)"],
"__atanhl":["long double","(long double)"],
"expl":["long double","(long double)"],
"__expl":["long double","(long double)"],
"frexpl":["long double","(long double, int *)"],
"__frexpl":["long double","(long double, int *)"],
"ldexpl":["long double","(long double, int)"],
"__ldexpl":["long double","(long double, int)"],
"logl":["long double","(long double)"],
"__logl":["long double","(long double)"],
"log10l":["long double","(long double)"],
"__log10l":["long double","(long double)"],
"modfl":["long double","(long double, long double *)"],
"__modfl":["long double","(long double, long double *)"],
"expm1l":["long double","(long double)"],
"__expm1l":["long double","(long double)"],
"log1pl":["long double","(long double)"],
"__log1pl":["long double","(long double)"],
"logbl":["long double","(long double)"],
"__logbl":["long double","(long double)"],
"exp2l":["long double","(long double)"],
"__exp2l":["long double","(long double)"],
"log2l":["long double","(long double)"],
"__log2l":["long double","(long double)"],
"powl":["long double","(long double, long double)"],
"__powl":["long double","(long double, long double)"],
"sqrtl":["long double","(long double)"],
"__sqrtl":["long double","(long double)"],
"hypotl":["long double","(long double, long double)"],
"__hypotl":["long double","(long double, long double)"],
"cbrtl":["long double","(long double)"],
"__cbrtl":["long double","(long double)"],
"ceill":["long double","(long double)"],
"__ceill":["long double","(long double)"],
"fabsl":["long double","(long double)"],
"__fabsl":["long double","(long double)"],
"floorl":["long double","(long double)"],
"__floorl":["long double","(long double)"],
"fmodl":["long double","(long double, long double)"],
"__fmodl":["long double","(long double, long double)"],
"isinfl":["int","(long double)"],
"finitel":["int","(long double)"],
"dreml":["long double","(long double, long double)"],
"__dreml":["long double","(long double, long double)"],
"significandl":["long double","(long double)"],
"__significandl":["long double","(long double)"],
"copysignl":["long double","(long double, long double)"],
"__copysignl":["long double","(long double, long double)"],
"nanl":["long double","(const char *)"],
"__nanl":["long double","(const char *)"],
"isnanl":["int","(long double)"],
"j0l":["long double","(long double)"],
"__j0l":["long double","(long double)"],
"j1l":["long double","(long double)"],
"__j1l":["long double","(long double)"],
"jnl":["long double","(int, long double)"],
"__jnl":["long double","(int, long double)"],
"y0l":["long double","(long double)"],
"__y0l":["long double","(long double)"],
"y1l":["long double","(long double)"],
"__y1l":["long double","(long double)"],
"ynl":["long double","(int, long double)"],
"__ynl":["long double","(int, long double)"],
"erfl":["long double","(long double)"],
"__erfl":["long double","(long double)"],
"erfcl":["long double","(long double)"],
"__erfcl":["long double","(long double)"],
"lgammal":["long double","(long double)"],
"__lgammal":["long double","(long double)"],
"tgammal":["long double","(long double)"],
"__tgammal":["long double","(long double)"],
"gammal":["long double","(long double)"],
"__gammal":["long double","(long double)"],
"lgammal_r":["long double","(long double, int *)"],
"__lgammal_r":["long double","(long double, int *)"],
"rintl":["long double","(long double)"],
"__rintl":["long double","(long double)"],
"nextafterl":["long double","(long double, long double)"],
"__nextafterl":["long double","(long double, long double)"],
"nexttowardl":["long double","(long double, long double)"],
"__nexttowardl":["long double","(long double, long double)"],
"remainderl":["long double","(long double, long double)"],
"__remainderl":["long double","(long double, long double)"],
"scalbnl":["long double","(long double, int)"],
"__scalbnl":["long double","(long double, int)"],
"ilogbl":["int","(long double)"],
"__ilogbl":["int","(long double)"],
"scalblnl":["long double","(long double, long)"],
"__scalblnl":["long double","(long double, long)"],
"nearbyintl":["long double","(long double)"],
"__nearbyintl":["long double","(long double)"],
"roundl":["long double","(long double)"],
"__roundl":["long double","(long double)"],
"truncl":["long double","(long double)"],
"__truncl":["long double","(long double)"],
"remquol":["long double","(long double, long double, int *)"],
"__remquol":["long double","(long double, long double, int *)"],
"lrintl":["long","(long double)"],
"__lrintl":["long","(long double)"],
"llrintl":["long long","(long double)"],
"__llrintl":["long long","(long double)"],
"lroundl":["long","(long double)"],
"__lroundl":["long","(long double)"],
"llroundl":["long long","(long double)"],
"__llroundl":["long long","(long double)"],
"fdiml":["long double","(long double, long double)"],
"__fdiml":["long double","(long double, long double)"],
"fmaxl":["long double","(long double, long double)"],
"__fmaxl":["long double","(long double, long double)"],
"fminl":["long double","(long double, long double)"],
"__fminl":["long double","(long double, long double)"],
"fmal":["long double","(long double, long double, long double)"],
"__fmal":["long double","(long double, long double, long double)"],
"scalbl":["long double","(long double, long double)"],
"__scalbl":["long double","(long double, long double)"],
"setjmp":["int","(struct __jmp_buf_tag *)"],
"__sigsetjmp":["int","(struct __jmp_buf_tag *, int)"],
"__sigsetjmp":["int","(struct __jmp_buf_tag *, int)"],
"_setjmp":["int","(struct __jmp_buf_tag *)"],
"longjmp":["void","(struct __jmp_buf_tag *, int)"],
"_longjmp":["void","(struct __jmp_buf_tag *, int)"],
"siglongjmp":["void","(struct __jmp_buf_tag *, int)"],
"__sysv_signal":["__sighandler_t","(int, __sighandler_t)"],
"signal":["__sighandler_t","(int, __sighandler_t)"],
"kill":["int","(__pid_t, int)"],
"killpg":["int","(__pid_t, int)"],
"raise":["int","(int)"],
"ssignal":["__sighandler_t","(int, __sighandler_t)"],
"gsignal":["int","(int)"],
"psignal":["void","(int, const char *)"],
"psiginfo":["void","(const siginfo_t *, const char *)"],
"sigblock":["int","(int)"],
"sigsetmask":["int","(int)"],
"siggetmask":["int","()"],
"sigemptyset":["int","(sigset_t *)"],
"sigfillset":["int","(sigset_t *)"],
"sigaddset":["int","(sigset_t *, int)"],
"sigdelset":["int","(sigset_t *, int)"],
"sigismember":["int","(const sigset_t *, int)"],
"sigprocmask":["int","(int, const sigset_t *restrict, sigset_t *restrict)"],
"sigsuspend":["int","(const sigset_t *)"],
"sigaction":["int","(int, const struct sigaction *restrict, struct sigaction *restrict)"],
"sigpending":["int","(sigset_t *)"],
"sigwait":["int","(const sigset_t *restrict, int *restrict)"],
"sigwaitinfo":["int","(const sigset_t *restrict, siginfo_t *restrict)"],
"sigtimedwait":["int","(const sigset_t *restrict, siginfo_t *restrict, const struct timespec *restrict)"],
"sigqueue":["int","(__pid_t, int, const union sigval)"],
"sigreturn":["int","(struct sigcontext *)"],
"siginterrupt":["int","(int, int)"],
"sigaltstack":["int","(const stack_t *restrict, stack_t *restrict)"],
"sigstack":["int","(struct sigstack *, struct sigstack *)"],
"pthread_sigmask":["int","(int, const __sigset_t *restrict, __sigset_t *restrict)"],
"pthread_kill":["int","(pthread_t, int)"],
"__libc_current_sigrtmin":["int","()"],
"__libc_current_sigrtmax":["int","()"],
"remove":["int","(const char *)"],
"rename":["int","(const char *, const char *)"],
"renameat":["int","(int, const char *, int, const char *)"],
"fclose":["int","(FILE *)"],
"tmpfile":["FILE *","()"],
"tmpnam":["char *","(char *)"],
"tmpnam_r":["char *","(char *)"],
"tempnam":["char *","(const char *, const char *)"],
"fflush":["int","(FILE *)"],
"fflush_unlocked":["int","(FILE *)"],
"fopen":["FILE *","(const char *restrict, const char *restrict)"],
"freopen":["FILE *","(const char *restrict, const char *restrict, FILE *restrict)"],
"fdopen":["FILE *","(int, const char *)"],
"fmemopen":["FILE *","(void *, size_t, const char *)"],
"open_memstream":["FILE *","(char **, size_t *)"],
"setbuf":["void","(FILE *restrict, char *restrict)"],
"setvbuf":["int","(FILE *restrict, char *restrict, int, size_t)"],
"setbuffer":["void","(FILE *restrict, char *restrict, size_t)"],
"setlinebuf":["void","(FILE *)"],
"fprintf":["int","(FILE *restrict, const char *restrict, ...)"],
"printf":["int","(const char *restrict, ...)"],
"sprintf":["int","(char *restrict, const char *restrict, ...)"],
"vfprintf":["int","(FILE *restrict, const char *restrict, struct __va_list_tag *)"],
"vprintf":["int","(const char *restrict, struct __va_list_tag *)"],
"vsprintf":["int","(char *restrict, const char *restrict, struct __va_list_tag *)"],
"snprintf":["int","(char *restrict, size_t, const char *restrict, ...)"],
"vsnprintf":["int","(char *restrict, size_t, const char *restrict, struct __va_list_tag *)"],
"vdprintf":["int","(int, const char *restrict, struct __va_list_tag *)"],
"dprintf":["int","(int, const char *restrict, ...)"],
"fscanf":["int","(FILE *restrict, const char *restrict, ...)"],
"fscanf":["int","(FILE *restrict, const char *restrict, ...)"],
"scanf":["int","(const char *restrict, ...)"],
"scanf":["int","(const char *restrict, ...)"],
"sscanf":["int","(const char *restrict, const char *restrict, ...)"],
"sscanf":["int","(const char *restrict, const char *restrict, ...)"],
"vfscanf":["int","(FILE *restrict, const char *restrict, struct __va_list_tag *)"],
"vfscanf":["int","(FILE *restrict, const char *restrict, struct __va_list_tag *)"],
"vscanf":["int","(const char *restrict, struct __va_list_tag *)"],
"vscanf":["int","(const char *restrict, struct __va_list_tag *)"],
"vsscanf":["int","(const char *restrict, const char *restrict, struct __va_list_tag *)"],
"vsscanf":["int","(const char *restrict, const char *restrict, struct __va_list_tag *)"],
"fgetc":["int","(FILE *)"],
"getc":["int","(FILE *)"],
"getchar":["int","()"],
"getc_unlocked":["int","(FILE *)"],
"getchar_unlocked":["int","()"],
"fgetc_unlocked":["int","(FILE *)"],
"fputc":["int","(int, FILE *)"],
"putc":["int","(int, FILE *)"],
"putchar":["int","(int)"],
"fputc_unlocked":["int","(int, FILE *)"],
"putc_unlocked":["int","(int, FILE *)"],
"putchar_unlocked":["int","(int)"],
"getw":["int","(FILE *)"],
"putw":["int","(int, FILE *)"],
"fgets":["char *","(char *restrict, int, FILE *restrict)"],
"__getdelim":["__ssize_t","(char **restrict, size_t *restrict, int, FILE *restrict)"],
"getdelim":["__ssize_t","(char **restrict, size_t *restrict, int, FILE *restrict)"],
"getline":["__ssize_t","(char **restrict, size_t *restrict, FILE *restrict)"],
"fputs":["int","(const char *restrict, FILE *restrict)"],
"puts":["int","(const char *)"],
"ungetc":["int","(int, FILE *)"],
"fread":["unsigned long","(void *restrict, size_t, size_t, FILE *restrict)"],
"fwrite":["unsigned long","(const void *restrict, size_t, size_t, FILE *restrict)"],
"fread_unlocked":["size_t","(void *restrict, size_t, size_t, FILE *restrict)"],
"fwrite_unlocked":["size_t","(const void *restrict, size_t, size_t, FILE *restrict)"],
"fseek":["int","(FILE *, long, int)"],
"ftell":["long","(FILE *)"],
"rewind":["void","(FILE *)"],
"fseeko":["int","(FILE *, __off_t, int)"],
"ftello":["__off_t","(FILE *)"],
"fgetpos":["int","(FILE *restrict, fpos_t *restrict)"],
"fsetpos":["int","(FILE *, const fpos_t *)"],
"clearerr":["void","(FILE *)"],
"feof":["int","(FILE *)"],
"ferror":["int","(FILE *)"],
"clearerr_unlocked":["void","(FILE *)"],
"feof_unlocked":["int","(FILE *)"],
"ferror_unlocked":["int","(FILE *)"],
"perror":["void","(const char *)"],
"fileno":["int","(FILE *)"],
"fileno_unlocked":["int","(FILE *)"],
"pclose":["int","(FILE *)"],
"popen":["FILE *","(const char *, const char *)"],
"ctermid":["char *","(char *)"],
"flockfile":["void","(FILE *)"],
"ftrylockfile":["int","(FILE *)"],
"funlockfile":["void","(FILE *)"],
"__uflow":["int","(FILE *)"],
"__overflow":["int","(FILE *, int)"],
"__ctype_get_mb_cur_max":["size_t","()"],
"atof":["double","(const char *)"],
"atoi":["int","(const char *)"],
"atol":["long","(const char *)"],
"atoll":["long long","(const char *)"],
"strtod":["double","(const char *restrict, char **restrict)"],
"strtof":["float","(const char *restrict, char **restrict)"],
"strtold":["long double","(const char *restrict, char **restrict)"],
"strtol":["long","(const char *restrict, char **restrict, int)"],
"strtoul":["unsigned long","(const char *restrict, char **restrict, int)"],
"strtoq":["long long","(const char *restrict, char **restrict, int)"],
"strtouq":["unsigned long long","(const char *restrict, char **restrict, int)"],
"strtoll":["long long","(const char *restrict, char **restrict, int)"],
"strtoull":["unsigned long long","(const char *restrict, char **restrict, int)"],
"l64a":["char *","(long)"],
"a64l":["long","(const char *)"],
"__bswap_16":["__uint16_t","(__uint16_t)"],
"__bswap_32":["__uint32_t","(__uint32_t)"],
"__bswap_64":["__uint64_t","(__uint64_t)"],
"__uint16_identity":["__uint16_t","(__uint16_t)"],
"__uint32_identity":["__uint32_t","(__uint32_t)"],
"__uint64_identity":["__uint64_t","(__uint64_t)"],
"select":["int","(int, fd_set *restrict, fd_set *restrict, fd_set *restrict, struct timeval *restrict)"],
"pselect":["int","(int, fd_set *restrict, fd_set *restrict, fd_set *restrict, const struct timespec *restrict, const __sigset_t *restrict)"],
"random":["long","()"],
"srandom":["void","(unsigned int)"],
"initstate":["char *","(unsigned int, char *, size_t)"],
"setstate":["char *","(char *)"],
"random_r":["int","(struct random_data *restrict, int32_t *restrict)"],
"srandom_r":["int","(unsigned int, struct random_data *)"],
"initstate_r":["int","(unsigned int, char *restrict, size_t, struct random_data *restrict)"],
"setstate_r":["int","(char *restrict, struct random_data *restrict)"],
"rand":["int","()"],
"srand":["void","(unsigned int)"],
"rand_r":["int","(unsigned int *)"],
"drand48":["double","()"],
"erand48":["double","(unsigned short *)"],
"lrand48":["long","()"],
"nrand48":["long","(unsigned short *)"],
"mrand48":["long","()"],
"jrand48":["long","(unsigned short *)"],
"srand48":["void","(long)"],
"seed48":["unsigned short *","(unsigned short *)"],
"lcong48":["void","(unsigned short *)"],
"drand48_r":["int","(struct drand48_data *restrict, double *restrict)"],
"erand48_r":["int","(unsigned short *, struct drand48_data *restrict, double *restrict)"],
"lrand48_r":["int","(struct drand48_data *restrict, long *restrict)"],
"nrand48_r":["int","(unsigned short *, struct drand48_data *restrict, long *restrict)"],
"mrand48_r":["int","(struct drand48_data *restrict, long *restrict)"],
"jrand48_r":["int","(unsigned short *, struct drand48_data *restrict, long *restrict)"],
"srand48_r":["int","(long, struct drand48_data *)"],
"seed48_r":["int","(unsigned short *, struct drand48_data *)"],
"lcong48_r":["int","(unsigned short *, struct drand48_data *)"],
"malloc":["void *","(size_t)"],
"calloc":["void *","(size_t, size_t)"],
"realloc":["void *","(void *, size_t)"],
"free":["void","(void *)"],
"reallocarray":["void *","(void *, size_t, size_t)"],
"reallocarray":["void *","(void *, size_t, size_t)"],
"alloca":["void *","(size_t)"],
"valloc":["void *","(size_t)"],
"posix_memalign":["int","(void **, size_t, size_t)"],
"aligned_alloc":["void *","(size_t, size_t)"],
"abort":["void","()"],
"atexit":["int","(void (*)(void))"],
"at_quick_exit":["int","(void (*)(void))"],
"on_exit":["int","(void (*)(int, void *), void *)"],
"exit":["void","(int)"],
"quick_exit":["void","(int)"],
"_Exit":["void","(int)"],
"getenv":["char *","(const char *)"],
"putenv":["int","(char *)"],
"setenv":["int","(const char *, const char *, int)"],
"unsetenv":["int","(const char *)"],
"clearenv":["int","()"],
"mktemp":["char *","(char *)"],
"mkstemp":["int","(char *)"],
"mkstemps":["int","(char *, int)"],
"mkdtemp":["char *","(char *)"],
"system":["int","(const char *)"],
"realpath":["char *","(const char *restrict, char *restrict)"],
"bsearch":["void *","(const void *, const void *, size_t, size_t, __compar_fn_t)"],
"qsort":["void","(void *, size_t, size_t, __compar_fn_t)"],
"abs":["int","(int)"],
"labs":["long","(long)"],
"llabs":["long long","(long long)"],
"div":["div_t","(int, int)"],
"ldiv":["ldiv_t","(long, long)"],
"lldiv":["lldiv_t","(long long, long long)"],
"ecvt":["char *","(double, int, int *restrict, int *restrict)"],
"fcvt":["char *","(double, int, int *restrict, int *restrict)"],
"gcvt":["char *","(double, int, char *)"],
"qecvt":["char *","(long double, int, int *restrict, int *restrict)"],
"qfcvt":["char *","(long double, int, int *restrict, int *restrict)"],
"qgcvt":["char *","(long double, int, char *)"],
"ecvt_r":["int","(double, int, int *restrict, int *restrict, char *restrict, size_t)"],
"fcvt_r":["int","(double, int, int *restrict, int *restrict, char *restrict, size_t)"],
"qecvt_r":["int","(long double, int, int *restrict, int *restrict, char *restrict, size_t)"],
"qfcvt_r":["int","(long double, int, int *restrict, int *restrict, char *restrict, size_t)"],
"mblen":["int","(const char *, size_t)"],
"mbtowc":["int","(wchar_t *restrict, const char *restrict, size_t)"],
"wctomb":["int","(char *, wchar_t)"],
"mbstowcs":["size_t","(wchar_t *restrict, const char *restrict, size_t)"],
"wcstombs":["size_t","(char *restrict, const wchar_t *restrict, size_t)"],
"rpmatch":["int","(const char *)"],
"getsubopt":["int","(char **restrict, char *const *restrict, char **restrict)"],
"getloadavg":["int","(double *, int)"],
"memcpy":["void *","(void *restrict, const void *restrict, size_t)"],
"memmove":["void *","(void *, const void *, size_t)"],
"memccpy":["void *","(void *restrict, const void *restrict, int, size_t)"],
"memset":["void *","(void *, int, size_t)"],
"memcmp":["int","(const void *, const void *, size_t)"],
"__memcmpeq":["int","(const void *, const void *, size_t)"],
"memchr":["void *","(const void *, int, size_t)"],
"strcpy":["char *","(char *restrict, const char *restrict)"],
"strncpy":["char *","(char *restrict, const char *restrict, size_t)"],
"strcat":["char *","(char *restrict, const char *restrict)"],
"strncat":["char *","(char *restrict, const char *restrict, size_t)"],
"strcmp":["int","(const char *, const char *)"],
"strncmp":["int","(const char *, const char *, size_t)"],
"strcoll":["int","(const char *, const char *)"],
"strxfrm":["unsigned long","(char *restrict, const char *restrict, size_t)"],
"strcoll_l":["int","(const char *, const char *, locale_t)"],
"strxfrm_l":["size_t","(char *, const char *, size_t, locale_t)"],
"strdup":["char *","(const char *)"],
"strndup":["char *","(const char *, size_t)"],
"strchr":["char *","(const char *, int)"],
"strrchr":["char *","(const char *, int)"],
"strcspn":["unsigned long","(const char *, const char *)"],
"strspn":["unsigned long","(const char *, const char *)"],
"strpbrk":["char *","(const char *, const char *)"],
"strstr":["char *","(const char *, const char *)"],
"strtok":["char *","(char *restrict, const char *restrict)"],
"__strtok_r":["char *","(char *restrict, const char *restrict, char **restrict)"],
"strtok_r":["char *","(char *restrict, const char *restrict, char **restrict)"],
"strlen":["unsigned long","(const char *)"],
"strnlen":["size_t","(const char *, size_t)"],
"strerror":["char *","(int)"],
"strerror_r":["int","(int, char *, size_t)"],
"strerror_l":["char *","(int, locale_t)"],
"bcmp":["int","(const void *, const void *, size_t)"],
"bcopy":["void","(const void *, void *, size_t)"],
"bzero":["void","(void *, size_t)"],
"index":["char *","(const char *, int)"],
"rindex":["char *","(const char *, int)"],
"ffs":["int","(int)"],
"ffsl":["int","(long)"],
"ffsll":["int","(long long)"],
"strcasecmp":["int","(const char *, const char *)"],
"strncasecmp":["int","(const char *, const char *, size_t)"],
"strcasecmp_l":["int","(const char *, const char *, locale_t)"],
"strncasecmp_l":["int","(const char *, const char *, size_t, locale_t)"],
"explicit_bzero":["void","(void *, size_t)"],
"strsep":["char *","(char **restrict, const char *restrict)"],
"strsignal":["char *","(int)"],
"__stpcpy":["char *","(char *restrict, const char *restrict)"],
"stpcpy":["char *","(char *restrict, const char *restrict)"],
"__stpncpy":["char *","(char *restrict, const char *restrict, size_t)"],
"stpncpy":["char *","(char *restrict, const char *restrict, size_t)"],
"clock":["clock_t","()"],
"time":["time_t","(time_t *)"],
"difftime":["double","(time_t, time_t)"],
"mktime":["time_t","(struct tm *)"],
"strftime":["size_t","(char *restrict, size_t, const char *restrict, const struct tm *restrict)"],
"strftime_l":["size_t","(char *restrict, size_t, const char *restrict, const struct tm *restrict, locale_t)"],
"gmtime":["struct tm *","(const time_t *)"],
"localtime":["struct tm *","(const time_t *)"],
"gmtime_r":["struct tm *","(const time_t *restrict, struct tm *restrict)"],
"localtime_r":["struct tm *","(const time_t *restrict, struct tm *restrict)"],
"asctime":["char *","(const struct tm *)"],
"ctime":["char *","(const time_t *)"],
"asctime_r":["char *","(const struct tm *restrict, char *restrict)"],
"ctime_r":["char *","(const time_t *restrict, char *restrict)"],
"tzset":["void","()"],
"timegm":["time_t","(struct tm *)"],
"timelocal":["time_t","(struct tm *)"],
"dysize":["int","(int)"],
"nanosleep":["int","(const struct timespec *, struct timespec *)"],
"clock_getres":["int","(clockid_t, struct timespec *)"],
"clock_gettime":["int","(clockid_t, struct timespec *)"],
"clock_settime":["int","(clockid_t, const struct timespec *)"],
"clock_nanosleep":["int","(clockid_t, int, const struct timespec *, struct timespec *)"],
"clock_getcpuclockid":["int","(pid_t, clockid_t *)"],
"timer_create":["int","(clockid_t, struct sigevent *restrict, timer_t *restrict)"],
"timer_delete":["int","(timer_t)"],
"timer_settime":["int","(timer_t, int, const struct itimerspec *restrict, struct itimerspec *restrict)"],
"timer_gettime":["int","(timer_t, struct itimerspec *)"],
"timer_getoverrun":["int","(timer_t)"],
"timespec_get":["int","(struct timespec *, int)"],
"wcscpy":["wchar_t *","(wchar_t *restrict, const wchar_t *restrict)"],
"wcsncpy":["wchar_t *","(wchar_t *restrict, const wchar_t *restrict, size_t)"],
"wcscat":["wchar_t *","(wchar_t *restrict, const wchar_t *restrict)"],
"wcsncat":["wchar_t *","(wchar_t *restrict, const wchar_t *restrict, size_t)"],
"wcscmp":["int","(const wchar_t *, const wchar_t *)"],
"wcsncmp":["int","(const wchar_t *, const wchar_t *, size_t)"],
"wcscasecmp":["int","(const wchar_t *, const wchar_t *)"],
"wcsncasecmp":["int","(const wchar_t *, const wchar_t *, size_t)"],
"wcscasecmp_l":["int","(const wchar_t *, const wchar_t *, locale_t)"],
"wcsncasecmp_l":["int","(const wchar_t *, const wchar_t *, size_t, locale_t)"],
"wcscoll":["int","(const wchar_t *, const wchar_t *)"],
"wcsxfrm":["size_t","(wchar_t *restrict, const wchar_t *restrict, size_t)"],
"wcscoll_l":["int","(const wchar_t *, const wchar_t *, locale_t)"],
"wcsxfrm_l":["size_t","(wchar_t *, const wchar_t *, size_t, locale_t)"],
"wcsdup":["wchar_t *","(const wchar_t *)"],
"wcschr":["int *","(const wchar_t *, wchar_t)"],
"wcsrchr":["wchar_t *","(const wchar_t *, wchar_t)"],
"wcscspn":["size_t","(const wchar_t *, const wchar_t *)"],
"wcsspn":["size_t","(const wchar_t *, const wchar_t *)"],
"wcspbrk":["wchar_t *","(const wchar_t *, const wchar_t *)"],
"wcsstr":["wchar_t *","(const wchar_t *, const wchar_t *)"],
"wcstok":["wchar_t *","(wchar_t *restrict, const wchar_t *restrict, wchar_t **restrict)"],
"wcslen":["unsigned long","(const wchar_t *)"],
"wcsnlen":["size_t","(const wchar_t *, size_t)"],
"wmemchr":["int *","(const wchar_t *, wchar_t, size_t)"],
"wmemcmp":["int","(const wchar_t *, const wchar_t *, size_t)"],
"wmemcpy":["int *","(wchar_t *restrict, const wchar_t *restrict, size_t)"],
"wmemmove":["int *","(wchar_t *, const wchar_t *, size_t)"],
"wmemset":["wchar_t *","(wchar_t *, wchar_t, size_t)"],
"btowc":["wint_t","(int)"],
"wctob":["int","(wint_t)"],
"mbsinit":["int","(const mbstate_t *)"],
"mbrtowc":["size_t","(wchar_t *restrict, const char *restrict, size_t, mbstate_t *restrict)"],
"wcrtomb":["size_t","(char *restrict, wchar_t, mbstate_t *restrict)"],
"__mbrlen":["size_t","(const char *restrict, size_t, mbstate_t *restrict)"],
"mbrlen":["size_t","(const char *restrict, size_t, mbstate_t *restrict)"],
"mbsrtowcs":["size_t","(wchar_t *restrict, const char **restrict, size_t, mbstate_t *restrict)"],
"wcsrtombs":["size_t","(char *restrict, const wchar_t **restrict, size_t, mbstate_t *restrict)"],
"mbsnrtowcs":["size_t","(wchar_t *restrict, const char **restrict, size_t, size_t, mbstate_t *restrict)"],
"wcsnrtombs":["size_t","(char *restrict, const wchar_t **restrict, size_t, size_t, mbstate_t *restrict)"],
"wcstod":["double","(const wchar_t *restrict, wchar_t **restrict)"],
"wcstof":["float","(const wchar_t *restrict, wchar_t **restrict)"],
"wcstold":["long double","(const wchar_t *restrict, wchar_t **restrict)"],
"wcstol":["long","(const wchar_t *restrict, wchar_t **restrict, int)"],
"wcstoul":["unsigned long","(const wchar_t *restrict, wchar_t **restrict, int)"],
"wcstoll":["long long","(const wchar_t *restrict, wchar_t **restrict, int)"],
"wcstoull":["unsigned long long","(const wchar_t *restrict, wchar_t **restrict, int)"],
"wcpcpy":["wchar_t *","(wchar_t *restrict, const wchar_t *restrict)"],
"wcpncpy":["wchar_t *","(wchar_t *restrict, const wchar_t *restrict, size_t)"],
"open_wmemstream":["__FILE *","(wchar_t **, size_t *)"],
"fwide":["int","(__FILE *, int)"],
"fwprintf":["int","(__FILE *restrict, const wchar_t *restrict, ...)"],
"wprintf":["int","(const wchar_t *restrict, ...)"],
"swprintf":["int","(wchar_t *restrict, size_t, const wchar_t *restrict, ...)"],
"vfwprintf":["int","(__FILE *restrict, const wchar_t *restrict, struct __va_list_tag *)"],
"vwprintf":["int","(const wchar_t *restrict, struct __va_list_tag *)"],
"vswprintf":["int","(wchar_t *restrict, size_t, const wchar_t *restrict, struct __va_list_tag *)"],
"fwscanf":["int","(__FILE *restrict, const wchar_t *restrict, ...)"],
"fwscanf":["int","(__FILE *restrict, const wchar_t *restrict, ...)"],
"wscanf":["int","(const wchar_t *restrict, ...)"],
"wscanf":["int","(const wchar_t *restrict, ...)"],
"swscanf":["int","(const wchar_t *restrict, const wchar_t *restrict, ...)"],
"swscanf":["int","(const wchar_t *restrict, const wchar_t *restrict, ...)"],
"vfwscanf":["int","(__FILE *restrict, const wchar_t *restrict, struct __va_list_tag *)"],
"vfwscanf":["int","(__FILE *restrict, const wchar_t *restrict, struct __va_list_tag *)"],
"vwscanf":["int","(const wchar_t *restrict, struct __va_list_tag *)"],
"vwscanf":["int","(const wchar_t *restrict, struct __va_list_tag *)"],
"vswscanf":["int","(const wchar_t *restrict, const wchar_t *restrict, struct __va_list_tag *)"],
"vswscanf":["int","(const wchar_t *restrict, const wchar_t *restrict, struct __va_list_tag *)"],
"fgetwc":["wint_t","(__FILE *)"],
"getwc":["wint_t","(__FILE *)"],
"getwchar":["wint_t","()"],
"fputwc":["wint_t","(wchar_t, __FILE *)"],
"putwc":["wint_t","(wchar_t, __FILE *)"],
"putwchar":["wint_t","(wchar_t)"],
"fgetws":["wchar_t *","(wchar_t *restrict, int, __FILE *restrict)"],
"fputws":["int","(const wchar_t *restrict, __FILE *restrict)"],
"ungetwc":["wint_t","(wint_t, __FILE *)"],
"wcsftime":["size_t","(wchar_t *restrict, size_t, const wchar_t *restrict, const struct tm *restrict)"],
"iswalnum":["int","(wint_t)"],
"iswalpha":["int","(wint_t)"],
"iswcntrl":["int","(wint_t)"],
"iswdigit":["int","(wint_t)"],
"iswgraph":["int","(wint_t)"],
"iswlower":["int","(wint_t)"],
"iswprint":["int","(wint_t)"],
"iswpunct":["int","(wint_t)"],
"iswspace":["int","(wint_t)"],
"iswupper":["int","(wint_t)"],
"iswxdigit":["int","(wint_t)"],
"iswblank":["int","(wint_t)"],
"wctype":["wctype_t","(const char *)"],
"iswctype":["int","(wint_t, wctype_t)"],
"towlower":["wint_t","(wint_t)"],
"towupper":["wint_t","(wint_t)"],
"wctrans":["wctrans_t","(const char *)"],
"towctrans":["wint_t","(wint_t, wctrans_t)"],
"iswalnum_l":["int","(wint_t, locale_t)"],
"iswalpha_l":["int","(wint_t, locale_t)"],
"iswcntrl_l":["int","(wint_t, locale_t)"],
"iswdigit_l":["int","(wint_t, locale_t)"],
"iswgraph_l":["int","(wint_t, locale_t)"],
"iswlower_l":["int","(wint_t, locale_t)"],
"iswprint_l":["int","(wint_t, locale_t)"],
"iswpunct_l":["int","(wint_t, locale_t)"],
"iswspace_l":["int","(wint_t, locale_t)"],
"iswupper_l":["int","(wint_t, locale_t)"],
"iswxdigit_l":["int","(wint_t, locale_t)"],
"iswblank_l":["int","(wint_t, locale_t)"],
"wctype_l":["wctype_t","(const char *, locale_t)"],
"iswctype_l":["int","(wint_t, wctype_t, locale_t)"],
"towlower_l":["wint_t","(wint_t, locale_t)"],
"towupper_l":["wint_t","(wint_t, locale_t)"],
"wctrans_l":["wctrans_t","(const char *, locale_t)"],
"towctrans_l":["wint_t","(wint_t, wctrans_t, locale_t)"],
"cacos":["_Complex double","(_Complex double)"],
"__cacos":["_Complex double","(_Complex double)"],
"casin":["_Complex double","(_Complex double)"],
"__casin":["_Complex double","(_Complex double)"],
"catan":["_Complex double","(_Complex double)"],
"__catan":["_Complex double","(_Complex double)"],
"ccos":["_Complex double","(_Complex double)"],
"__ccos":["_Complex double","(_Complex double)"],
"csin":["_Complex double","(_Complex double)"],
"__csin":["_Complex double","(_Complex double)"],
"ctan":["_Complex double","(_Complex double)"],
"__ctan":["_Complex double","(_Complex double)"],
"cacosh":["_Complex double","(_Complex double)"],
"__cacosh":["_Complex double","(_Complex double)"],
"casinh":["_Complex double","(_Complex double)"],
"__casinh":["_Complex double","(_Complex double)"],
"catanh":["_Complex double","(_Complex double)"],
"__catanh":["_Complex double","(_Complex double)"],
"ccosh":["_Complex double","(_Complex double)"],
"__ccosh":["_Complex double","(_Complex double)"],
"csinh":["_Complex double","(_Complex double)"],
"__csinh":["_Complex double","(_Complex double)"],
"ctanh":["_Complex double","(_Complex double)"],
"__ctanh":["_Complex double","(_Complex double)"],
"cexp":["_Complex double","(_Complex double)"],
"__cexp":["_Complex double","(_Complex double)"],
"clog":["_Complex double","(_Complex double)"],
"__clog":["_Complex double","(_Complex double)"],
"cpow":["_Complex double","(_Complex double, _Complex double)"],
"__cpow":["_Complex double","(_Complex double, _Complex double)"],
"csqrt":["_Complex double","(_Complex double)"],
"__csqrt":["_Complex double","(_Complex double)"],
"cabs":["double","(_Complex double)"],
"__cabs":["double","(_Complex double)"],
"carg":["double","(_Complex double)"],
"__carg":["double","(_Complex double)"],
"conj":["_Complex double","(_Complex double)"],
"__conj":["_Complex double","(_Complex double)"],
"cproj":["_Complex double","(_Complex double)"],
"__cproj":["_Complex double","(_Complex double)"],
"cimag":["double","(_Complex double)"],
"__cimag":["double","(_Complex double)"],
"creal":["double","(_Complex double)"],
"__creal":["double","(_Complex double)"],
"cacosf":["_Complex float","(_Complex float)"],
"__cacosf":["_Complex float","(_Complex float)"],
"casinf":["_Complex float","(_Complex float)"],
"__casinf":["_Complex float","(_Complex float)"],
"catanf":["_Complex float","(_Complex float)"],
"__catanf":["_Complex float","(_Complex float)"],
"ccosf":["_Complex float","(_Complex float)"],
"__ccosf":["_Complex float","(_Complex float)"],
"csinf":["_Complex float","(_Complex float)"],
"__csinf":["_Complex float","(_Complex float)"],
"ctanf":["_Complex float","(_Complex float)"],
"__ctanf":["_Complex float","(_Complex float)"],
"cacoshf":["_Complex float","(_Complex float)"],
"__cacoshf":["_Complex float","(_Complex float)"],
"casinhf":["_Complex float","(_Complex float)"],
"__casinhf":["_Complex float","(_Complex float)"],
"catanhf":["_Complex float","(_Complex float)"],
"__catanhf":["_Complex float","(_Complex float)"],
"ccoshf":["_Complex float","(_Complex float)"],
"__ccoshf":["_Complex float","(_Complex float)"],
"csinhf":["_Complex float","(_Complex float)"],
"__csinhf":["_Complex float","(_Complex float)"],
"ctanhf":["_Complex float","(_Complex float)"],
"__ctanhf":["_Complex float","(_Complex float)"],
"cexpf":["_Complex float","(_Complex float)"],
"__cexpf":["_Complex float","(_Complex float)"],
"clogf":["_Complex float","(_Complex float)"],
"__clogf":["_Complex float","(_Complex float)"],
"cpowf":["_Complex float","(_Complex float, _Complex float)"],
"__cpowf":["_Complex float","(_Complex float, _Complex float)"],
"csqrtf":["_Complex float","(_Complex float)"],
"__csqrtf":["_Complex float","(_Complex float)"],
"cabsf":["float","(_Complex float)"],
"__cabsf":["float","(_Complex float)"],
"cargf":["float","(_Complex float)"],
"__cargf":["float","(_Complex float)"],
"conjf":["_Complex float","(_Complex float)"],
"__conjf":["_Complex float","(_Complex float)"],
"cprojf":["_Complex float","(_Complex float)"],
"__cprojf":["_Complex float","(_Complex float)"],
"cimagf":["float","(_Complex float)"],
"__cimagf":["float","(_Complex float)"],
"crealf":["float","(_Complex float)"],
"__crealf":["float","(_Complex float)"],
"cacosl":["_Complex long double","(_Complex long double)"],
"__cacosl":["_Complex long double","(_Complex long double)"],
"casinl":["_Complex long double","(_Complex long double)"],
"__casinl":["_Complex long double","(_Complex long double)"],
"catanl":["_Complex long double","(_Complex long double)"],
"__catanl":["_Complex long double","(_Complex long double)"],
"ccosl":["_Complex long double","(_Complex long double)"],
"__ccosl":["_Complex long double","(_Complex long double)"],
"csinl":["_Complex long double","(_Complex long double)"],
"__csinl":["_Complex long double","(_Complex long double)"],
"ctanl":["_Complex long double","(_Complex long double)"],
"__ctanl":["_Complex long double","(_Complex long double)"],
"cacoshl":["_Complex long double","(_Complex long double)"],
"__cacoshl":["_Complex long double","(_Complex long double)"],
"casinhl":["_Complex long double","(_Complex long double)"],
"__casinhl":["_Complex long double","(_Complex long double)"],
"catanhl":["_Complex long double","(_Complex long double)"],
"__catanhl":["_Complex long double","(_Complex long double)"],
"ccoshl":["_Complex long double","(_Complex long double)"],
"__ccoshl":["_Complex long double","(_Complex long double)"],
"csinhl":["_Complex long double","(_Complex long double)"],
"__csinhl":["_Complex long double","(_Complex long double)"],
"ctanhl":["_Complex long double","(_Complex long double)"],
"__ctanhl":["_Complex long double","(_Complex long double)"],
"cexpl":["_Complex long double","(_Complex long double)"],
"__cexpl":["_Complex long double","(_Complex long double)"],
"clogl":["_Complex long double","(_Complex long double)"],
"__clogl":["_Complex long double","(_Complex long double)"],
"cpowl":["_Complex long double","(_Complex long double, _Complex long double)"],
"__cpowl":["_Complex long double","(_Complex long double, _Complex long double)"],
"csqrtl":["_Complex long double","(_Complex long double)"],
"__csqrtl":["_Complex long double","(_Complex long double)"],
"cabsl":["long double","(_Complex long double)"],
"__cabsl":["long double","(_Complex long double)"],
"cargl":["long double","(_Complex long double)"],
"__cargl":["long double","(_Complex long double)"],
"conjl":["_Complex long double","(_Complex long double)"],
"__conjl":["_Complex long double","(_Complex long double)"],
"cprojl":["_Complex long double","(_Complex long double)"],
"__cprojl":["_Complex long double","(_Complex long double)"],
"cimagl":["long double","(_Complex long double)"],
"__cimagl":["long double","(_Complex long double)"],
"creall":["long double","(_Complex long double)"],
"__creall":["long double","(_Complex long double)"],
"feclearexcept":["int","(int)"],
"fegetexceptflag":["int","(fexcept_t *, int)"],
"feraiseexcept":["int","(int)"],
"fesetexceptflag":["int","(const fexcept_t *, int)"],
"fetestexcept":["int","(int)"],
"fegetround":["int","()"],
"fesetround":["int","(int)"],
"fegetenv":["int","(fenv_t *)"],
"feholdexcept":["int","(fenv_t *)"],
"fesetenv":["int","(const fenv_t *)"],
"feupdateenv":["int","(const fenv_t *)"],
"imaxabs":["intmax_t","(intmax_t)"],
"imaxdiv":["imaxdiv_t","(intmax_t, intmax_t)"],
"strtoimax":["intmax_t","(const char *restrict, char **restrict, int)"],
"strtoumax":["uintmax_t","(const char *restrict, char **restrict, int)"],
"wcstoimax":["intmax_t","(const __gwchar_t *restrict, __gwchar_t **restrict, int)"],
"wcstoumax":["uintmax_t","(const __gwchar_t *restrict, __gwchar_t **restrict, int)"],
"__tg_promote":["_Argument_type_is_not_arithmetic","(...)"],
"__tg_promote":["double","(int)"],
"__tg_promote":["double","(unsigned int)"],
"__tg_promote":["double","(long)"],
"__tg_promote":["double","(unsigned long)"],
"__tg_promote":["double","(long long)"],
"__tg_promote":["double","(unsigned long long)"],
"__tg_promote":["float","(float)"],
"__tg_promote":["double","(double)"],
"__tg_promote":["long double","(long double)"],
"__tg_promote":["_Complex float","(_Complex float)"],
"__tg_promote":["_Complex double","(_Complex double)"],
"__tg_promote":["_Complex long double","(_Complex long double)"],
"__tg_acos":["float","(float)"],
"__tg_acos":["double","(double)"],
"__tg_acos":["long double","(long double)"],
"__tg_acos":["_Complex float","(_Complex float)"],
"__tg_acos":["_Complex double","(_Complex double)"],
"__tg_acos":["_Complex long double","(_Complex long double)"],
"__tg_asin":["float","(float)"],
"__tg_asin":["double","(double)"],
"__tg_asin":["long double","(long double)"],
"__tg_asin":["_Complex float","(_Complex float)"],
"__tg_asin":["_Complex double","(_Complex double)"],
"__tg_asin":["_Complex long double","(_Complex long double)"],
"__tg_atan":["float","(float)"],
"__tg_atan":["double","(double)"],
"__tg_atan":["long double","(long double)"],
"__tg_atan":["_Complex float","(_Complex float)"],
"__tg_atan":["_Complex double","(_Complex double)"],
"__tg_atan":["_Complex long double","(_Complex long double)"],
"__tg_acosh":["float","(float)"],
"__tg_acosh":["double","(double)"],
"__tg_acosh":["long double","(long double)"],
"__tg_acosh":["_Complex float","(_Complex float)"],
"__tg_acosh":["_Complex double","(_Complex double)"],
"__tg_acosh":["_Complex long double","(_Complex long double)"],
"__tg_asinh":["float","(float)"],
"__tg_asinh":["double","(double)"],
"__tg_asinh":["long double","(long double)"],
"__tg_asinh":["_Complex float","(_Complex float)"],
"__tg_asinh":["_Complex double","(_Complex double)"],
"__tg_asinh":["_Complex long double","(_Complex long double)"],
"__tg_atanh":["float","(float)"],
"__tg_atanh":["double","(double)"],
"__tg_atanh":["long double","(long double)"],
"__tg_atanh":["_Complex float","(_Complex float)"],
"__tg_atanh":["_Complex double","(_Complex double)"],
"__tg_atanh":["_Complex long double","(_Complex long double)"],
"__tg_cos":["float","(float)"],
"__tg_cos":["double","(double)"],
"__tg_cos":["long double","(long double)"],
"__tg_cos":["_Complex float","(_Complex float)"],
"__tg_cos":["_Complex double","(_Complex double)"],
"__tg_cos":["_Complex long double","(_Complex long double)"],
"__tg_sin":["float","(float)"],
"__tg_sin":["double","(double)"],
"__tg_sin":["long double","(long double)"],
"__tg_sin":["_Complex float","(_Complex float)"],
"__tg_sin":["_Complex double","(_Complex double)"],
"__tg_sin":["_Complex long double","(_Complex long double)"],
"__tg_tan":["float","(float)"],
"__tg_tan":["double","(double)"],
"__tg_tan":["long double","(long double)"],
"__tg_tan":["_Complex float","(_Complex float)"],
"__tg_tan":["_Complex double","(_Complex double)"],
"__tg_tan":["_Complex long double","(_Complex long double)"],
"__tg_cosh":["float","(float)"],
"__tg_cosh":["double","(double)"],
"__tg_cosh":["long double","(long double)"],
"__tg_cosh":["_Complex float","(_Complex float)"],
"__tg_cosh":["_Complex double","(_Complex double)"],
"__tg_cosh":["_Complex long double","(_Complex long double)"],
"__tg_sinh":["float","(float)"],
"__tg_sinh":["double","(double)"],
"__tg_sinh":["long double","(long double)"],
"__tg_sinh":["_Complex float","(_Complex float)"],
"__tg_sinh":["_Complex double","(_Complex double)"],
"__tg_sinh":["_Complex long double","(_Complex long double)"],
"__tg_tanh":["float","(float)"],
"__tg_tanh":["double","(double)"],
"__tg_tanh":["long double","(long double)"],
"__tg_tanh":["_Complex float","(_Complex float)"],
"__tg_tanh":["_Complex double","(_Complex double)"],
"__tg_tanh":["_Complex long double","(_Complex long double)"],
"__tg_exp":["float","(float)"],
"__tg_exp":["double","(double)"],
"__tg_exp":["long double","(long double)"],
"__tg_exp":["_Complex float","(_Complex float)"],
"__tg_exp":["_Complex double","(_Complex double)"],
"__tg_exp":["_Complex long double","(_Complex long double)"],
"__tg_log":["float","(float)"],
"__tg_log":["double","(double)"],
"__tg_log":["long double","(long double)"],
"__tg_log":["_Complex float","(_Complex float)"],
"__tg_log":["_Complex double","(_Complex double)"],
"__tg_log":["_Complex long double","(_Complex long double)"],
"__tg_pow":["float","(float, float)"],
"__tg_pow":["double","(double, double)"],
"__tg_pow":["long double","(long double, long double)"],
"__tg_pow":["_Complex float","(_Complex float, _Complex float)"],
"__tg_pow":["_Complex double","(_Complex double, _Complex double)"],
"__tg_pow":["_Complex long double","(_Complex long double, _Complex long double)"],
"__tg_sqrt":["float","(float)"],
"__tg_sqrt":["double","(double)"],
"__tg_sqrt":["long double","(long double)"],
"__tg_sqrt":["_Complex float","(_Complex float)"],
"__tg_sqrt":["_Complex double","(_Complex double)"],
"__tg_sqrt":["_Complex long double","(_Complex long double)"],
"__tg_fabs":["float","(float)"],
"__tg_fabs":["double","(double)"],
"__tg_fabs":["long double","(long double)"],
"__tg_fabs":["float","(_Complex float)"],
"__tg_fabs":["double","(_Complex double)"],
"__tg_fabs":["long double","(_Complex long double)"],
"__tg_atan2":["float","(float, float)"],
"__tg_atan2":["double","(double, double)"],
"__tg_atan2":["long double","(long double, long double)"],
"__tg_cbrt":["float","(float)"],
"__tg_cbrt":["double","(double)"],
"__tg_cbrt":["long double","(long double)"],
"__tg_ceil":["float","(float)"],
"__tg_ceil":["double","(double)"],
"__tg_ceil":["long double","(long double)"],
"__tg_copysign":["float","(float, float)"],
"__tg_copysign":["double","(double, double)"],
"__tg_copysign":["long double","(long double, long double)"],
"__tg_erf":["float","(float)"],
"__tg_erf":["double","(double)"],
"__tg_erf":["long double","(long double)"],
"__tg_erfc":["float","(float)"],
"__tg_erfc":["double","(double)"],
"__tg_erfc":["long double","(long double)"],
"__tg_exp2":["float","(float)"],
"__tg_exp2":["double","(double)"],
"__tg_exp2":["long double","(long double)"],
"__tg_expm1":["float","(float)"],
"__tg_expm1":["double","(double)"],
"__tg_expm1":["long double","(long double)"],
"__tg_fdim":["float","(float, float)"],
"__tg_fdim":["double","(double, double)"],
"__tg_fdim":["long double","(long double, long double)"],
"__tg_floor":["float","(float)"],
"__tg_floor":["double","(double)"],
"__tg_floor":["long double","(long double)"],
"__tg_fma":["float","(float, float, float)"],
"__tg_fma":["double","(double, double, double)"],
"__tg_fma":["long double","(long double, long double, long double)"],
"__tg_fmax":["float","(float, float)"],
"__tg_fmax":["double","(double, double)"],
"__tg_fmax":["long double","(long double, long double)"],
"__tg_fmin":["float","(float, float)"],
"__tg_fmin":["double","(double, double)"],
"__tg_fmin":["long double","(long double, long double)"],
"__tg_fmod":["float","(float, float)"],
"__tg_fmod":["double","(double, double)"],
"__tg_fmod":["long double","(long double, long double)"],
"__tg_frexp":["float","(float, int *)"],
"__tg_frexp":["double","(double, int *)"],
"__tg_frexp":["long double","(long double, int *)"],
"__tg_hypot":["float","(float, float)"],
"__tg_hypot":["double","(double, double)"],
"__tg_hypot":["long double","(long double, long double)"],
"__tg_ilogb":["int","(float)"],
"__tg_ilogb":["int","(double)"],
"__tg_ilogb":["int","(long double)"],
"__tg_ldexp":["float","(float, int)"],
"__tg_ldexp":["double","(double, int)"],
"__tg_ldexp":["long double","(long double, int)"],
"__tg_lgamma":["float","(float)"],
"__tg_lgamma":["double","(double)"],
"__tg_lgamma":["long double","(long double)"],
"__tg_llrint":["long long","(float)"],
"__tg_llrint":["long long","(double)"],
"__tg_llrint":["long long","(long double)"],
"__tg_llround":["long long","(float)"],
"__tg_llround":["long long","(double)"],
"__tg_llround":["long long","(long double)"],
"__tg_log10":["float","(float)"],
"__tg_log10":["double","(double)"],
"__tg_log10":["long double","(long double)"],
"__tg_log1p":["float","(float)"],
"__tg_log1p":["double","(double)"],
"__tg_log1p":["long double","(long double)"],
"__tg_log2":["float","(float)"],
"__tg_log2":["double","(double)"],
"__tg_log2":["long double","(long double)"],
"__tg_logb":["float","(float)"],
"__tg_logb":["double","(double)"],
"__tg_logb":["long double","(long double)"],
"__tg_lrint":["long","(float)"],
"__tg_lrint":["long","(double)"],
"__tg_lrint":["long","(long double)"],
"__tg_lround":["long","(float)"],
"__tg_lround":["long","(double)"],
"__tg_lround":["long","(long double)"],
"__tg_nearbyint":["float","(float)"],
"__tg_nearbyint":["double","(double)"],
"__tg_nearbyint":["long double","(long double)"],
"__tg_nextafter":["float","(float, float)"],
"__tg_nextafter":["double","(double, double)"],
"__tg_nextafter":["long double","(long double, long double)"],
"__tg_nexttoward":["float","(float, long double)"],
"__tg_nexttoward":["double","(double, long double)"],
"__tg_nexttoward":["long double","(long double, long double)"],
"__tg_remainder":["float","(float, float)"],
"__tg_remainder":["double","(double, double)"],
"__tg_remainder":["long double","(long double, long double)"],
"__tg_remquo":["float","(float, float, int *)"],
"__tg_remquo":["double","(double, double, int *)"],
"__tg_remquo":["long double","(long double, long double, int *)"],
"__tg_rint":["float","(float)"],
"__tg_rint":["double","(double)"],
"__tg_rint":["long double","(long double)"],
"__tg_round":["float","(float)"],
"__tg_round":["double","(double)"],
"__tg_round":["long double","(long double)"],
"__tg_scalbn":["float","(float, int)"],
"__tg_scalbn":["double","(double, int)"],
"__tg_scalbn":["long double","(long double, int)"],
"__tg_scalbln":["float","(float, long)"],
"__tg_scalbln":["double","(double, long)"],
"__tg_scalbln":["long double","(long double, long)"],
"__tg_tgamma":["float","(float)"],
"__tg_tgamma":["double","(double)"],
"__tg_tgamma":["long double","(long double)"],
"__tg_trunc":["float","(float)"],
"__tg_trunc":["double","(double)"],
"__tg_trunc":["long double","(long double)"],
"__tg_carg":["float","(float)"],
"__tg_carg":["double","(double)"],
"__tg_carg":["long double","(long double)"],
"__tg_carg":["float","(_Complex float)"],
"__tg_carg":["double","(_Complex double)"],
"__tg_carg":["long double","(_Complex long double)"],
"__tg_cimag":["float","(float)"],
"__tg_cimag":["double","(double)"],
"__tg_cimag":["long double","(long double)"],
"__tg_cimag":["float","(_Complex float)"],
"__tg_cimag":["double","(_Complex double)"],
"__tg_cimag":["long double","(_Complex long double)"],
"__tg_conj":["_Complex float","(float)"],
"__tg_conj":["_Complex double","(double)"],
"__tg_conj":["_Complex long double","(long double)"],
"__tg_conj":["_Complex float","(_Complex float)"],
"__tg_conj":["_Complex double","(_Complex double)"],
"__tg_conj":["_Complex long double","(_Complex long double)"],
"__tg_cproj":["_Complex float","(float)"],
"__tg_cproj":["_Complex double","(double)"],
"__tg_cproj":["_Complex long double","(long double)"],
"__tg_cproj":["_Complex float","(_Complex float)"],
"__tg_cproj":["_Complex double","(_Complex double)"],
"__tg_cproj":["_Complex long double","(_Complex long double)"],
"__tg_creal":["float","(float)"],
"__tg_creal":["double","(double)"],
"__tg_creal":["long double","(long double)"],
"__tg_creal":["float","(_Complex float)"],
"__tg_creal":["double","(_Complex double)"],
"__tg_creal":["long double","(_Complex long double)"],
"mbrtoc16":["size_t","(char16_t *restrict, const char *restrict, size_t, mbstate_t *restrict)"],
"c16rtomb":["size_t","(char *restrict, char16_t, mbstate_t *restrict)"],
"mbrtoc32":["size_t","(char32_t *restrict, const char *restrict, size_t, mbstate_t *restrict)"],
"c32rtomb":["size_t","(char *restrict, char32_t, mbstate_t *restrict)"],
"access":["int","(const char *, int)"],
"faccessat":["int","(int, const char *, int, int)"],
"lseek":["__off_t","(int, __off_t, int)"],
"close":["int","(int)"],
"closefrom":["void","(int)"],
"read":["ssize_t","(int, void *, size_t)"],
"write":["ssize_t","(int, const void *, size_t)"],
"pread":["ssize_t","(int, void *, size_t, __off_t)"],
"pwrite":["ssize_t","(int, const void *, size_t, __off_t)"],
"pipe":["int","(int *)"],
"alarm":["unsigned int","(unsigned int)"],
"sleep":["unsigned int","(unsigned int)"],
"ualarm":["__useconds_t","(__useconds_t, __useconds_t)"],
"usleep":["int","(__useconds_t)"],
"pause":["int","()"],
"chown":["int","(const char *, __uid_t, __gid_t)"],
"fchown":["int","(int, __uid_t, __gid_t)"],
"lchown":["int","(const char *, __uid_t, __gid_t)"],
"fchownat":["int","(int, const char *, __uid_t, __gid_t, int)"],
"chdir":["int","(const char *)"],
"fchdir":["int","(int)"],
"getcwd":["char *","(char *, size_t)"],
"getwd":["char *","(char *)"],
"dup":["int","(int)"],
"dup2":["int","(int, int)"],
"execve":["int","(const char *, char *const *, char *const *)"],
"fexecve":["int","(int, char *const *, char *const *)"],
"execv":["int","(const char *, char *const *)"],
"execle":["int","(const char *, const char *, ...)"],
"execl":["int","(const char *, const char *, ...)"],
"execvp":["int","(const char *, char *const *)"],
"execlp":["int","(const char *, const char *, ...)"],
"nice":["int","(int)"],
"_exit":["void","(int)"],
"pathconf":["long","(const char *, int)"],
"fpathconf":["long","(int, int)"],
"sysconf":["long","(int)"],
"confstr":["size_t","(int, char *, size_t)"],
"getpid":["__pid_t","()"],
"getppid":["__pid_t","()"],
"getpgrp":["__pid_t","()"],
"__getpgid":["__pid_t","(__pid_t)"],
"getpgid":["__pid_t","(__pid_t)"],
"setpgid":["int","(__pid_t, __pid_t)"],
"setpgrp":["int","()"],
"setsid":["__pid_t","()"],
"getsid":["__pid_t","(__pid_t)"],
"getuid":["__uid_t","()"],
"geteuid":["__uid_t","()"],
"getgid":["__gid_t","()"],
"getegid":["__gid_t","()"],
"getgroups":["int","(int, __gid_t *)"],
"setuid":["int","(__uid_t)"],
"setreuid":["int","(__uid_t, __uid_t)"],
"seteuid":["int","(__uid_t)"],
"setgid":["int","(__gid_t)"],
"setregid":["int","(__gid_t, __gid_t)"],
"setegid":["int","(__gid_t)"],
"fork":["__pid_t","()"],
"vfork":["int","()"],
"ttyname":["char *","(int)"],
"ttyname_r":["int","(int, char *, size_t)"],
"isatty":["int","(int)"],
"ttyslot":["int","()"],
"link":["int","(const char *, const char *)"],
"linkat":["int","(int, const char *, int, const char *, int)"],
"symlink":["int","(const char *, const char *)"],
"readlink":["ssize_t","(const char *restrict, char *restrict, size_t)"],
"symlinkat":["int","(const char *, int, const char *)"],
"readlinkat":["ssize_t","(int, const char *restrict, char *restrict, size_t)"],
"unlink":["int","(const char *)"],
"unlinkat":["int","(int, const char *, int)"],
"rmdir":["int","(const char *)"],
"tcgetpgrp":["__pid_t","(int)"],
"tcsetpgrp":["int","(int, __pid_t)"],
"getlogin":["char *","()"],
"getlogin_r":["int","(char *, size_t)"],
"setlogin":["int","(const char *)"],
"getopt":["int","(int, char *const *, const char *)"],
"gethostname":["int","(char *, size_t)"],
"sethostname":["int","(const char *, size_t)"],
"sethostid":["int","(long)"],
"getdomainname":["int","(char *, size_t)"],
"setdomainname":["int","(const char *, size_t)"],
"vhangup":["int","()"],
"revoke":["int","(const char *)"],
"profil":["int","(unsigned short *, size_t, size_t, unsigned int)"],
"acct":["int","(const char *)"],
"getusershell":["char *","()"],
"endusershell":["void","()"],
"setusershell":["void","()"],
"daemon":["int","(int, int)"],
"chroot":["int","(const char *)"],
"getpass":["char *","(const char *)"],
"fsync":["int","(int)"],
"gethostid":["long","()"],
"sync":["void","()"],
"getpagesize":["int","()"],
"getdtablesize":["int","()"],
"truncate":["int","(const char *, __off_t)"],
"ftruncate":["int","(int, __off_t)"],
"brk":["int","(void *)"],
"sbrk":["void *","(intptr_t)"],
"syscall":["long","(long, ...)"],
"lockf":["int","(int, int, __off_t)"],
"fdatasync":["int","(int)"],
"crypt":["char *","(const char *, const char *)"],
"getentropy":["int","(void *, size_t)"],
"stat":["int","(const char *restrict, struct stat *restrict)"],
"fstat":["int","(int, struct stat *)"],
"fstatat":["int","(int, const char *restrict, struct stat *restrict, int)"],
"lstat":["int","(const char *restrict, struct stat *restrict)"],
"chmod":["int","(const char *, __mode_t)"],
"lchmod":["int","(const char *, __mode_t)"],
"fchmod":["int","(int, __mode_t)"],
"fchmodat":["int","(int, const char *, __mode_t, int)"],
"umask":["__mode_t","(__mode_t)"],
"mkdir":["int","(const char *, __mode_t)"],
"mkdirat":["int","(int, const char *, __mode_t)"],
"mknod":["int","(const char *, __mode_t, __dev_t)"],
"mknodat":["int","(int, const char *, __mode_t, __dev_t)"],
"mkfifo":["int","(const char *, __mode_t)"],
"mkfifoat":["int","(int, const char *, __mode_t)"],
"utimensat":["int","(int, const char *, const struct timespec *, int)"],
"futimens":["int","(int, const struct timespec *)"],
"wait":["__pid_t","(int *)"],
"waitpid":["__pid_t","(__pid_t, int *, int)"],
"waitid":["int","(idtype_t, __id_t, siginfo_t *, int)"],
"wait3":["__pid_t","(int *, int, struct rusage *)"],
"wait4":["__pid_t","(__pid_t, int *, int, struct rusage *)"],
"ioctl":["int","(int, unsigned long, ...)"],
"gettimeofday":["int","(struct timeval *restrict, void *restrict)"],
"settimeofday":["int","(const struct timeval *, const struct timezone *)"],
"adjtime":["int","(const struct timeval *, struct timeval *)"],
"getitimer":["int","(__itimer_which_t, struct itimerval *)"],
"setitimer":["int","(__itimer_which_t, const struct itimerval *restrict, struct itimerval *restrict)"],
"utimes":["int","(const char *, const struct timeval *)"],
"lutimes":["int","(const char *, const struct timeval *)"],
"futimes":["int","(int, const struct timeval *)"],
"times":["clock_t","(struct tms *)"],
"getrlimit":["int","(__rlimit_resource_t, struct rlimit *)"],
"setrlimit":["int","(__rlimit_resource_t, const struct rlimit *)"],
"getrusage":["int","(__rusage_who_t, struct rusage *)"],
"getpriority":["int","(__priority_which_t, id_t)"],
"setpriority":["int","(__priority_which_t, id_t, int)"],
"fcntl":["int","(int, int, ...)"],
"open":["int","(const char *, int, ...)"],
"openat":["int","(int, const char *, int, ...)"],
"creat":["int","(const char *, mode_t)"],
"posix_fadvise":["int","(int, off_t, off_t, int)"],
"posix_fallocate":["int","(int, off_t, off_t)"],
"__sched_cpucount":["int","(size_t, const cpu_set_t *)"],
"__sched_cpualloc":["cpu_set_t *","(size_t)"],
"__sched_cpufree":["void","(cpu_set_t *)"],
"sched_setparam":["int","(__pid_t, const struct sched_param *)"],
"sched_getparam":["int","(__pid_t, struct sched_param *)"],
"sched_setscheduler":["int","(__pid_t, int, const struct sched_param *)"],
"sched_getscheduler":["int","(__pid_t)"],
"sched_yield":["int","()"],
"sched_get_priority_max":["int","(int)"],
"sched_get_priority_min":["int","(int)"],
"sched_rr_get_interval":["int","(__pid_t, struct timespec *)"],
"pthread_create":["int","(pthread_t *restrict, const pthread_attr_t *restrict, void *(*)(void *), void *restrict)"],
"pthread_exit":["void","(void *)"],
"pthread_join":["int","(pthread_t, void **)"],
"pthread_detach":["int","(pthread_t)"],
"pthread_self":["pthread_t","()"],
"pthread_equal":["int","(pthread_t, pthread_t)"],
"pthread_attr_init":["int","(pthread_attr_t *)"],
"pthread_attr_destroy":["int","(pthread_attr_t *)"],
"pthread_attr_getdetachstate":["int","(const pthread_attr_t *, int *)"],
"pthread_attr_setdetachstate":["int","(pthread_attr_t *, int)"],
"pthread_attr_getguardsize":["int","(const pthread_attr_t *, size_t *)"],
"pthread_attr_setguardsize":["int","(pthread_attr_t *, size_t)"],
"pthread_attr_getschedparam":["int","(const pthread_attr_t *restrict, struct sched_param *restrict)"],
"pthread_attr_setschedparam":["int","(pthread_attr_t *restrict, const struct sched_param *restrict)"],
"pthread_attr_getschedpolicy":["int","(const pthread_attr_t *restrict, int *restrict)"],
"pthread_attr_setschedpolicy":["int","(pthread_attr_t *, int)"],
"pthread_attr_getinheritsched":["int","(const pthread_attr_t *restrict, int *restrict)"],
"pthread_attr_setinheritsched":["int","(pthread_attr_t *, int)"],
"pthread_attr_getscope":["int","(const pthread_attr_t *restrict, int *restrict)"],
"pthread_attr_setscope":["int","(pthread_attr_t *, int)"],
"pthread_attr_getstackaddr":["int","(const pthread_attr_t *restrict, void **restrict)"],
"pthread_attr_setstackaddr":["int","(pthread_attr_t *, void *)"],
"pthread_attr_getstacksize":["int","(const pthread_attr_t *restrict, size_t *restrict)"],
"pthread_attr_setstacksize":["int","(pthread_attr_t *, size_t)"],
"pthread_attr_getstack":["int","(const pthread_attr_t *restrict, void **restrict, size_t *restrict)"],
"pthread_attr_setstack":["int","(pthread_attr_t *, void *, size_t)"],
"pthread_setschedparam":["int","(pthread_t, int, const struct sched_param *)"],
"pthread_getschedparam":["int","(pthread_t, int *restrict, struct sched_param *restrict)"],
"pthread_setschedprio":["int","(pthread_t, int)"],
"pthread_once":["int","(pthread_once_t *, void (*)(void))"],
"pthread_setcancelstate":["int","(int, int *)"],
"pthread_setcanceltype":["int","(int, int *)"],
"pthread_cancel":["int","(pthread_t)"],
"pthread_testcancel":["void","()"],
"__pthread_register_cancel":["void","(__pthread_unwind_buf_t *)"],
"__pthread_unregister_cancel":["void","(__pthread_unwind_buf_t *)"],
"__pthread_unwind_next":["void","(__pthread_unwind_buf_t *)"],
"pthread_mutex_init":["int","(pthread_mutex_t *, const pthread_mutexattr_t *)"],
"pthread_mutex_destroy":["int","(pthread_mutex_t *)"],
"pthread_mutex_trylock":["int","(pthread_mutex_t *)"],
"pthread_mutex_lock":["int","(pthread_mutex_t *)"],
"pthread_mutex_timedlock":["int","(pthread_mutex_t *restrict, const struct timespec *restrict)"],
"pthread_mutex_unlock":["int","(pthread_mutex_t *)"],
"pthread_mutex_getprioceiling":["int","(const pthread_mutex_t *restrict, int *restrict)"],
"pthread_mutex_setprioceiling":["int","(pthread_mutex_t *restrict, int, int *restrict)"],
"pthread_mutex_consistent":["int","(pthread_mutex_t *)"],
"pthread_mutexattr_init":["int","(pthread_mutexattr_t *)"],
"pthread_mutexattr_destroy":["int","(pthread_mutexattr_t *)"],
"pthread_mutexattr_getpshared":["int","(const pthread_mutexattr_t *restrict, int *restrict)"],
"pthread_mutexattr_setpshared":["int","(pthread_mutexattr_t *, int)"],
"pthread_mutexattr_gettype":["int","(const pthread_mutexattr_t *restrict, int *restrict)"],
"pthread_mutexattr_settype":["int","(pthread_mutexattr_t *, int)"],
"pthread_mutexattr_getprotocol":["int","(const pthread_mutexattr_t *restrict, int *restrict)"],
"pthread_mutexattr_setprotocol":["int","(pthread_mutexattr_t *, int)"],
"pthread_mutexattr_getprioceiling":["int","(const pthread_mutexattr_t *restrict, int *restrict)"],
"pthread_mutexattr_setprioceiling":["int","(pthread_mutexattr_t *, int)"],
"pthread_mutexattr_getrobust":["int","(const pthread_mutexattr_t *, int *)"],
"pthread_mutexattr_setrobust":["int","(pthread_mutexattr_t *, int)"],
"pthread_rwlock_init":["int","(pthread_rwlock_t *restrict, const pthread_rwlockattr_t *restrict)"],
"pthread_rwlock_destroy":["int","(pthread_rwlock_t *)"],
"pthread_rwlock_rdlock":["int","(pthread_rwlock_t *)"],
"pthread_rwlock_tryrdlock":["int","(pthread_rwlock_t *)"],
"pthread_rwlock_timedrdlock":["int","(pthread_rwlock_t *restrict, const struct timespec *restrict)"],
"pthread_rwlock_wrlock":["int","(pthread_rwlock_t *)"],
"pthread_rwlock_trywrlock":["int","(pthread_rwlock_t *)"],
"pthread_rwlock_timedwrlock":["int","(pthread_rwlock_t *restrict, const struct timespec *restrict)"],
"pthread_rwlock_unlock":["int","(pthread_rwlock_t *)"],
"pthread_rwlockattr_init":["int","(pthread_rwlockattr_t *)"],
"pthread_rwlockattr_destroy":["int","(pthread_rwlockattr_t *)"],
"pthread_rwlockattr_getpshared":["int","(const pthread_rwlockattr_t *restrict, int *restrict)"],
"pthread_rwlockattr_setpshared":["int","(pthread_rwlockattr_t *, int)"],
"pthread_rwlockattr_getkind_np":["int","(const pthread_rwlockattr_t *restrict, int *restrict)"],
"pthread_rwlockattr_setkind_np":["int","(pthread_rwlockattr_t *, int)"],
"pthread_cond_init":["int","(pthread_cond_t *restrict, const pthread_condattr_t *restrict)"],
"pthread_cond_destroy":["int","(pthread_cond_t *)"],
"pthread_cond_signal":["int","(pthread_cond_t *)"],
"pthread_cond_broadcast":["int","(pthread_cond_t *)"],
"pthread_cond_wait":["int","(pthread_cond_t *restrict, pthread_mutex_t *restrict)"],
"pthread_cond_timedwait":["int","(pthread_cond_t *restrict, pthread_mutex_t *restrict, const struct timespec *restrict)"],
"pthread_condattr_init":["int","(pthread_condattr_t *)"],
"pthread_condattr_destroy":["int","(pthread_condattr_t *)"],
"pthread_condattr_getpshared":["int","(const pthread_condattr_t *restrict, int *restrict)"],
"pthread_condattr_setpshared":["int","(pthread_condattr_t *, int)"],
"pthread_condattr_getclock":["int","(const pthread_condattr_t *restrict, __clockid_t *restrict)"],
"pthread_condattr_setclock":["int","(pthread_condattr_t *, __clockid_t)"],
"pthread_spin_init":["int","(pthread_spinlock_t *, int)"],
"pthread_spin_destroy":["int","(pthread_spinlock_t *)"],
"pthread_spin_lock":["int","(pthread_spinlock_t *)"],
"pthread_spin_trylock":["int","(pthread_spinlock_t *)"],
"pthread_spin_unlock":["int","(pthread_spinlock_t *)"],
"pthread_barrier_init":["int","(pthread_barrier_t *restrict, const pthread_barrierattr_t *restrict, unsigned int)"],
"pthread_barrier_destroy":["int","(pthread_barrier_t *)"],
"pthread_barrier_wait":["int","(pthread_barrier_t *)"],
"pthread_barrierattr_init":["int","(pthread_barrierattr_t *)"],
"pthread_barrierattr_destroy":["int","(pthread_barrierattr_t *)"],
"pthread_barrierattr_getpshared":["int","(const pthread_barrierattr_t *restrict, int *restrict)"],
"pthread_barrierattr_setpshared":["int","(pthread_barrierattr_t *, int)"],
"pthread_key_create":["int","(pthread_key_t *, void (*)(void *))"],
"pthread_key_delete":["int","(pthread_key_t)"],
"pthread_getspecific":["void *","(pthread_key_t)"],
"pthread_setspecific":["int","(pthread_key_t, const void *)"],
"pthread_getcpuclockid":["int","(pthread_t, __clockid_t *)"],
"pthread_atfork":["int","(void (*)(void), void (*)(void), void (*)(void))"],
"opendir":["DIR *","(const char *)"],
"fdopendir":["DIR *","(int)"],
"closedir":["int","(DIR *)"],
"readdir":["struct dirent *","(DIR *)"],
"readdir_r":["int","(DIR *restrict, struct dirent *restrict, struct dirent **restrict)"],
"rewinddir":["void","(DIR *)"],
"seekdir":["void","(DIR *, long)"],
"telldir":["long","(DIR *)"],
"dirfd":["int","(DIR *)"],
"scandir":["int","(const char *restrict, struct dirent ***restrict, int (*)(const struct dirent *), int (*)(const struct dirent **, const struct dirent **))"],
"alphasort":["int","(const struct dirent **, const struct dirent **)"],
"getdirentries":["__ssize_t","(int, char *restrict, size_t, __off_t *restrict)"],
"_obstack_newchunk":["void","(struct obstack *, int)"],
"_obstack_begin":["int","(struct obstack *, int, int, void *(*)(long), void (*)(void *))"],
"_obstack_begin_1":["int","(struct obstack *, int, int, void *(*)(void *, long), void (*)(void *, void *), void *)"],
"_obstack_memory_used":["int","(struct obstack *)"],
"obstack_free":["void","(struct obstack *, void *)"],
"getopt_long":["int","(int, char *const *, const char *, const struct option *, int *)"],
"getopt_long_only":["int","(int, char *const *, const char *, const struct option *, int *)"],
"catopen":["nl_catd","(const char *, int)"],
"catgets":["char *","(nl_catd, int, int, const char *)"],
"catclose":["int","(nl_catd)"],
"__printf_chk":["int","(int flag, const char *format, ...)"],
"__cxa_finalize":["void","(void *dso_handle)"],
"__strncat_chk":["char *","(char *dest, const char *src, size_t n, size_t destlen)"],
"__vsnprintf_chk":["int","(char *str, size_t size, int flag, size_t strlen, const char *format, va_list ap)"],
"__isoc99_sscanf":["int","(const char *str, const char *format, ...)"],
"__stack_chk_fail":["void","(void)"],
"__fprintf_chk":["int","(FILE *stream, int flag, const char *format, ...)"],
"__libc_start_main":["int","(int (*main)(int, char **, char **), int argc, char **argv, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void (*stack_end))"],
"__strcat_chk":["char *", "(char *dest, const char *src, size_t destlen)"],
"__vfprintf_chk":["int", "(FILE *s, const char *format, va_list ap, int flags, int width)"],
"__strcpy_chk":["char *", "(char *dest, const char *src, size_t destlen)"],
"__sprintf_chk":["int", "(char *str, int flags, size_t slen, const char *format, ...)"],
"__snprintf_chk": ["int", "(char *dest, size_t destlen, int flag, size_t size, const char *format, ...)"],
"__memcpy_chk":["void*", "(void *dest, const void src, size_t len, size_t destlen)"],
"__strncpy_chk":["char", "(char *dest, const char *src, size_t n, size_t destlen)"],
"__isoc99_vfscanf":["int", "(FILE *stream, const char *format, va_list arg)"],
"__isoc99_vsscanf":["int", "(const char *str, const char *format, va_list arg)"],
"__xstat":["int","(int ver, const char *path, struct stat *buf)"],
"__fxstat":["int","(int ver, int fd, struct stat *buf)"],
  }

