"__printf_chk":["int","(int flag, const char *format, ...)"],
"__cxa_finalize":["void","(void *dso_handle)"],
"__strncat_chk":["char *","(char *dest, const char *src, size_t n, size_t destlen)"],
"__vsnprintf_chk":["int","(char *str, size_t size, int flag, size_t strlen, const char *format, va_list ap)"],
"__isoc99_sscanf":["int","(const char *str, const char *format, ...)"],
"__stack_chk_fail":["void","(void)"],
"__fprintf_chk":["int","(FILE *stream, int flag, const char *format, ...)"],
"__libc_start_main":["int","(int (*main)(int, char **, char **), int argc, char **argv, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void (*stack_end))"],
"__strcat_chk":["char *", "(char *dest, const char *src, size_t destlen)"],
"__vfprintf_chk":["int", "(FILE *s,int flag, const char *format, va_list ap)"],
"__strcpy_chk":["char *", "(char *dest, const char *src, size_t destlen)"],
"__sprintf_chk":["int", "(char *str, int flags, size_t slen, const char *format, ...)"],
"__snprintf_chk": ["int", "(char *dest, size_t destlen, int flag, size_t size, const char *format, ...)"],
"__memcpy_chk":["void*", "(void *dest, const void *src, size_t len, size_t destlen)"],
"__strncpy_chk":["char", "(char *dest, const char *src, size_t n, size_t destlen)"],
"__isoc99_vfscanf":["int", "(FILE *stream, const char *format, va_list arg)"],
"__isoc99_vsscanf":["int", "(const char *str, const char *format, va_list arg)"],
"__xstat":["int","(int ver, const char *path, struct stat *buf)"],
"__fxstat":["int","(int ver, int fd, struct stat *buf)"],
"__memset_chk":["void *","(void * dest, int c, size_t len, size_t destlen)"],
"__asprintf_chk":["int","(char **result_ptr, int flag, const char *format, ...)"],
"__fread_chk":["size_t","(void *__restrict ptr, size_t ptrlen,size_t size, size_t n, FILE *__restrict stream)"],
"__vasprintf_chk":["int","(char **result_ptr, int flag, const char *format, va_list ap)"],
"__cxa_atexit":["int","(void (*func) (void *), void * arg, void * dso_handle)"],
"__realpath_chk":["char *","(const char * path, char * resolved_path, size_t resolved_len)"],
"__longjmp_chk":["void","(jmp_buf env, int val)"],
"__vsprintf_chk":["int","(char * s, int flag, size_t slen, const char * format, va_list args)"],
"__memmove_chk":["void *","(void * dest, const void * src, size_t len, size_t destlen)"],
"__fdelt_chk":["long int","(long int d)"],
"__isoc99_scanf":["int","(const char *format, ...)"],
